### ISSUE TITLE
Trouble building on NixOS

### ISSUE THREAD

**Issue by bbarker** [cprussin/nixjs#3] opened 2019-03-06 20:23 UTC
CC @paluh , following up on https://github.com/NixOS/nixpkgs/issues/42833 - thanks for offering to have a look.

(I also had trouble building on Ubuntu with Nix, but didn't get a good error message there - so not 100% sure it is the same issue).

**Symptom:**

```
Data.Conduit.Zlib
  Data.Conduit.Zlib
    idempotent
      +++ OK, passed 100 tests.
    flush
      +++ OK, passed 100 tests.
    compressFlush large data
    uncompressed after compressed
    multiple compressed values
    single compressed, multiple uncompressed chunks
    multiple, over 32k

Failures:

  test/Data/Conduit/Process/TypedSpec.hs:11:3:
  1) Data.Conduit.Process.Typed cat works
       uncaught exception: ExitCodeException
       Received ExitFailure (-15) when running
       Raw command: cat ChangeLog.md

  To rerun use: --match "/Data.Conduit.Process.Typed/cat works/"

Randomized with seed 1535173165

Finished in 5.7955 seconds
132 examples, 1 failure
Test suite test: FAIL
Test suite logged to: dist/test/conduit-extra-1.3.0-test.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for '/nix/store/8xj8312lhm16pg5vdcbf08j2dx6wqmly-conduit-extra-1.3.0.drv' failed with exit code 1
cannot build derivation '/nix/store/15mchi3fwi3phwa0b249wzc6sankz09j-monad-logger-0.3.29.drv': 1 dependencies couldn't be built
building '/nix/store/bf7g7bnwpz0fq57dv8nxlh76q69yc395-vault-0.3.1.2.drv'...
cannot build derivation '/nix/store/1mjy3vhnz38n6apd1bm65w1s5gw873a8-purescript-0.12.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/1mjy3vhnz38n6apd1bm65w1s5gw873a8-purescript-0.12.2.drv' failed
```

I also tried with purescript at 0.12.1.

This occurs when I run the following nix-shell script:

```nix
File Edit Options Buffers Tools Help                                                                                                                                               
{
  nodejsVersion ? "10.14.1",
  yarnVersion ? "1.12.3",
  purescriptVersion ? "0.12.2",
  nixjs ? fetchTarball "https://github.com/cprussin/nixjs/archive/0.0.7.tar.gz",                                                                                                  
  # nixpkgs ? (import ./pkgs.nix) # or change to: ? <nixpkgs>
  # how to get this to work?
  nixpkgs ? <nixpkgs>
}:


with import nixpkgs {
  overlays = [
    (import nixjs {
      nodejs = nodejsVersion;
      yarn = yarnVersion;
      purescript = purescriptVersion;
    })
  ];
};

mkShell {
  buildInputs = [
    nodejs yarn purescript
    nodePackages.bower
    nodePackages.pulp
    psc-package
  ];
}
```
Failure appears to be with building conduit-extra; I can do `nix-shell -p haskellPackages.conduit-extra` but this just copies them from cache.nixos.org - no compilation is needed.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.95, NixOS, 18.09.1985.749a3a0d00b (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(nixos): `""`
 - channels(root): `"nixos-18.09.1985.749a3a0d00b"`
 - channels(brandon): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by cprussin** [comment] 2019-03-06 22:56
Thanks for the detailed report!  Nothing stands out to me at first glance here and I've done all my testing while building this by working on nixos 18.09... by any chance can you try a `nixos-rebuild switch --upgrade` and then try re-running this shell?

**Comment by cprussin** [comment] 2019-03-06 22:57
FWIW I've got this confirmed working on `18.09.2247.3276e04a39e (Jellyfish)` with the following shell file: https://github.com/cprussin/purescript-httpure/blob/e64565e497394a1505c863fc3824bb56cb1ffba3/shell.nix

I've also tested shell files that look the same as that one but with nodejs and yarn versions locked as well and I haven't run into this issue

**Comment by bbarker** [comment] 2019-03-07 01:48
@cprussin thanks for checking!

So looks like I have the same error after the upgrade:

```
Data.Conduit.Zlib
  Data.Conduit.Zlib
    idempotent
      +++ OK, passed 100 tests.
    flush
      +++ OK, passed 100 tests.
    compressFlush large data
    uncompressed after compressed
    multiple compressed values
    single compressed, multiple uncompressed chunks
    multiple, over 32k

Failures:

  test/Data/Conduit/Process/TypedSpec.hs:11:3:
  1) Data.Conduit.Process.Typed cat works
       uncaught exception: ExitCodeException
       Received ExitFailure (-15) when running
       Raw command: cat ChangeLog.md

  To rerun use: --match "/Data.Conduit.Process.Typed/cat works/"

Randomized with seed 1053601126

Finished in 5.8430 seconds
132 examples, 1 failure
Test suite test: FAIL
Test suite logged to: dist/test/conduit-extra-1.3.0-test.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for '/nix/store/8qgnpsk8sykmvqiz5swgq654bshvizz1-conduit-extra-1.3.0.drv' failed with exit code 1
cannot build derivation '/nix/store/jcnx6la3bj16yzklnfwd474rmcbqdsl7-monad-logger-0.3.29.drv': 1 dependencies couldn't be built
building '/nix/store/7yjs75jq4cxcgm1k60mamv6w4l84acxc-vault-0.3.1.2.drv'...
cannot build derivation '/nix/store/gnrhi9jyw7y39wpg4mpdg4n31y3iqdzd-purescript-0.12.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/gnrhi9jyw7y39wpg4mpdg4n31y3iqdzd-purescript-0.12.2.drv' failed
```

**System info after upgrade:**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.95, NixOS, 18.09.2317.18fec2687c0 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(nixos): `""`
 - channels(root): `"nixos-18.09.2317.18fec2687c0"`
 - channels(brandon): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I then tried your exact nix-shell file and had the same result (this finished much more quickly as most things seemed to be cached in the local /nix/store at this point).

**Comment by cprussin** [comment] 2019-03-07 05:19
Huh, looks like a known issue in `conduit-extra` that was reported here: https://github.com/snoyberg/conduit/issues/385.  I'm not sure how to fix this in nixjs, I'm guessing either we would need to wait for the upstream fix to the test or maybe do an overlay on nixpkgs to override conduit with a custom package that disables tests.

**Comment by cprussin** [comment] 2019-03-07 05:26
More data: looks like this has happened in hydra builds for nixpkgs in the past and was treated as a transient failure (see https://github.com/NixOS/nixpkgs/issues/47218) so I'm not convinced this has anything to do with nixjs at all other than that you're recompiling that package instead of using the cache.  I'll continue doing some research but for now I think this is a bug in nixpkgs, not nixjs (though maybe we could put in some kind of workaround like I mentioned in the last comment in nixjs--I'd be open to that if we could figure out a way to do it)

**Comment by cprussin** [comment] 2019-03-09 20:32
I'm going to close this ticket since this issue looks pretty well confirmed to be an issue in `conduit` itself, that would potentially affect all nix builds, whether or not you're using `nixjs`.  I'm still open to putting a workaround into nixjs and would accept a PR if you wanted to put one in @bbarker , but I don't think this is worth tracking as a nixjs issue.

**Closed as completed by cprussin** 2019-03-09 20:32 UTC
